baseURL = 'https://waycrate.dev/'
languageCode = 'en-US'
title = 'Waycrate'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'GitHub'
pageRef = 'https://github.com/waycrate/'
wieght = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
